#!/usr/bin/env python
from wisegcn.handler import process_gcn
import lxml.etree

print("Assuming MS181101ab-1-Preliminary.xml is in the working directory")
filename = 'MS181101ab-1-Preliminary.xml'

payload = open(filename, 'rb').read()
root = lxml.etree.fromstring(payload)
process_gcn(payload, root)
